global using Microsoft.Win32;
global using Serilog;
global using Serilog.Configuration;
global using Serilog.Core;
global using Serilog.Events;
global using System.Diagnostics;
global using System.IO.Compression;
global using System.Security.Principal;
global using System.Text.Json;