name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: cd build && build.bat
      shell: cmd

    - name: Upload artifact Sirstrap.CLI
      uses: actions/upload-artifact@v4
      with:
        name: Sirstrap.CLI
        path: out/Sirstrap.CLI

    - name: Upload artifact Sirstrap.UI
      uses: actions/upload-artifact@v4
      with:
        name: Sirstrap.UI
        path: out/Sirstrap.UI