name: Develop Branch Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      security-events: write
    uses: ./.github/workflows/_build.yml
    with:
      run-security-scan: true
