name: Main Branch Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    permissions:
      id-token: write
      security-events: write
    uses: ./.github/workflows/_build.yml
